all:
	make -C jxj/
	make -C p2p_tutk/
	make -C p2p_vivi/
	make -C dianxin/

clean:
	make clean -C jxj/
	make clean -C p2p_tutk/
	make clean -C p2p_vivi/
	make clean -C dianxin/

install:
	make install -C jxj/
	make install -C p2p_tutk/
	make install -C p2p_vivi/
	make install -C dianxin/

.PHONY: all clean install


